travis:
  secure:
    BINSTAR_TOKEN: cvnDf9ah7V8TJZShRS3SlkQCEMRElNbAHWyYrFax+jUZBj992W3+wcIwkvZvNYx1V9Iz+fYSWpJoj5Aub3uf6VjSm67m1oVVcwDpx0g4LbsNeG5XreXkZK4BP1nFUNwMTFjWgPmZ35rYz7jZ4vg8NkaZFCMB37bwzZMx5uB8YhzDcc/8JlsXFk9n3nLVcfdxIJZzBWm5iguU60TKHIEqUBcFsqHscpJZEMX6XFn3LiY0qg2nz886CBF/SoM6+OaUl6E4hqrVAyLm9j7tRQqQsHAypymSOouFhJWErc+DooNKUtKlmsEgLFh1RCpwjr5zLhRNTIc91JZu3GwI0ht31d2UmCoeSOtygg+Z6sdDO0BzVnsb0Ng/zUr37f7eUddxv41Ip6xQ2bBmPT0AvUr+QBEvAvt6N2He9p27/2u0XJm3hoUw8hYe0YnChiCE5mS9cUAqUDj/v1LKnUVDpDyzGLwaKmGux3ONA4KBmBqZPbPmcCbc0m7zHDipF4t3S52TdazgxUIwnsgYgfs+FuPxdVbO2I70VkBUu9yfAYoRN/iBtmgbUwlRbFI+0sz1equx/PDT+ff2z7pfMkkRG5cMI+mfAA32N62B+U9n3if7h2caQzyBISoes3kx4MQryC7VRLaLu8z7Rsz9NAazPAa+rH1kX/Ig9jNiT6/NqIpY/B8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
