travis:
  secure:
    BINSTAR_TOKEN: Jx47JSrOlnTtvw7ypBL8GRueNWhLXbxDZNYB8QftEtHDzBIHr4/yoiDivh7LHsPDfsCzlarpXVh687LmX3+DV8MTtHHyQ7LfLMtdvc/iLCQ2GzBcYNwCpa89WQYG8+0IxudkVKfaAjYm0BtoYkn3K/VPGXFXPBcZr2pGKlKiv+nWhC9NsgXApfOyhykI7cPSAZa1izLBT0tHpYxCoXxWZryireJvtC8kg3ywQrCb8Yw1Ck8XcsVhrTRk8RCXS/NonloT2Umf0j/P1Y6lmhOP2h4x9IR7P2y8NVIKSJG+TbfrY7pLgyIng03B1pfIaAWIXp1/Rvq9Asf3yjz0scNxBVJ2c/dL0L8p0YcS0t2jQgjg+vjtv7XQ9+vMKDMX8m14unMINvAZgy+zmEam9InSMmmKi5KWQD7GwZwvwzHGYtenV/h2LVJ45+3jn2ADboSmHtkN6Cp0FJuLSUCZH+oVKr1XEPnIIMnH4b+fobSmjTcVrAwr+6lagOdYZA3rbekgJ035DNgRsglriA6nQgyoPmmhVPiN+mTLf4aVpH8MwV1CG2VEIyS1uRJRxzAuyguS13uZ09t+kbxN0edvSKz5vpW/8KK7Qvp1+CK4Y1HOsfB2eUWmASH5cS3KtUcR6ukKvhSxE+2+VNa9Ls1M9xYGpSX7rjPQ2U4+ec91athFcqs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
