travis:
  secure:
    BINSTAR_TOKEN: BM3sYToeujChGWL55jeX8m7lLoJpjnnJowSaC3wN1uNpUzoJ44X9Eo6THHlZ/A6LM9+tTHBJzV1g7oUJ/LGaRQhaFYAWohOYAXF4fV/ii8ooURpyLnC1QmTWjQ4QYsiS30cT1c+3//PopO42pplBfJRGFPMqvJaJSocY6rBcknX6VAzKcTa6Qp3R/yzI8ptLwS193UhebQZ0RCS06zpkMiTuEBy54qKvGnuOMKXIHPGxtKDnI8OG5zFtZcvNdd+aULgYjjuBZMa8KGIkxDtTvb27zgBTQyOZO+h3o2kaRHc0xDxujd8WQuz8RoXWG8G75ackPnzOZTUCRDzwRDyqMCDWqsfPAYcaYwM3NGqGOxV1HR+e/3crqcniwh80LjC5fJgWux6LKnH2hYDVbUiXa5h6WkJAqneZEvq7eqnGkQWTdnnhdwKwf3g2+BkbwyPaMPv9ZFNijg0N4tkLCEaF2pDz63l3A6a9hToFb9zUORWXbxfTJle9rTITzu6+gWegpxTv/h4NE/qeZOMDYYJgTrUk5ChTm/K4OESTmnofJ0jFwFcewKyMRAqsdOC9+42p1qnbkwlCtNy4c1oxioUJfHmQj+LgLtbC2pMZbirbRKeO/Nppiii5gQpyplH1p2hDQNc5KWEsDC/Hk264XHH3oKtAOmVUu67mzElYrQcbly4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
